Updating the github actions.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,5 +1,4 @@
 # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
-# Copied from www.github.com/google/flax
 # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
 
 name: Build
@@ -14,37 +13,122 @@ on:
       - main
 
 jobs:
-  build:
+  cancel-previous:
+    name: Cancel Previous Runs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Cancel previous
+        uses: styfle/cancel-workflow-action@0.10.1
+        if: ${{github.ref != 'refs/head/main'}}
+        with:
+          access_token: ${{ github.token }}
+  pre-commit:
+    name: Test pre-commit hooks
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.7
+      - uses: pre-commit/action@v2.0.3
+  commit-count:
+    name: Check commit count
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    # We allow at most 5 commits in a branch to ensure our CI doesn't break.
+    - name: Check commit count in PR
+      if: always()
+      shell: bash
+      run: |
+        set -x
+        # $GITHUB_REF is in format `refs/heads/<branch_name>`. We fetch it under
+        # the name `commit-count` so we can refer to it below.
+        # Do an unshallow fetch so we retrieve all commits (this is necessary
+        # because ations/checkout@v2 fetches a shallow copy).
+        git fetch origin --unshallow $GITHUB_REF:commit-count
+        git fetch origin main
+        diff=$(git rev-list --count origin/main...commit-count)
+        # $GITHUB_REF adds an additional commit to the commit tree, so $diff is
+        # one too high when executing this as a Github Action.
+        if (( $diff > 6)); then
+          echo "ERROR! More than 5 commits in PR -- please squash your commits."
+          url=https://flax.readthedocs.io/en/latest/contributing.html#too-many-commits-in-a-pr
+          echo "See $url for help on how to resolve this."
+          exit 1
+        fi
+  test-import:
+    name: Test import standalone
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: [3.7]
+        python-version: [3.7, 3.8, 3.9]
     steps:
-    - name: Cancel previous
-      uses: styfle/cancel-workflow-action@0.8.0
-      with:
-        access_token: ${{ github.token }}
-    - name: Install native dependencies
-      run: |
-        sudo apt-get -y install pandoc
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v1
+      uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
+    - name: Install standalone dependencies only
       run: |
         pip install .
-        pip install .[testing]
-        pip install pytest
-        pip install pytest-xdist
-        pip install pytest-cov
-        pip install optax
-        pip install netCDF4
-    - name: Test with pytest and generate coverage report
+    - name: Test importing JAX MD
       run: |
-        JAX_ENABLE_X64=1 pytest -n auto --cov=jax_md --cov-report=xml --cov-report=term --cov-config=setup.cfg
+        python -c "import jax_md"
+  tests:
+    name: Run Tests
+    needs: [cancel-previous, pre-commit, commit-count, test-import]
+    runs-on: ubuntu-20.04-16core
+    strategy:
+      matrix:
+        python-version: [3.7, 3.8, 3.9]
+        test-type: [pytest, pytype]
+        exclude:
+          - test-type: pytype
+            python-version: 3.7
+          - test-type: pytype
+            python-version: 3.8
+    steps:
+    - uses: actions/checkout@v3
+    - name: Set up Python ${{ matrix.python-version }}
+      id: setup_python
+      uses: actions/setup-python@v4
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Get week and year
+      id: week_year
+      run: echo "DATE=$(date +%U-%Y)" >> $GITHUB_OUTPUT
+    - name: Cached virtual environment
+      id: venv_cache
+      uses: actions/cache@v3
+      with:
+        path: venv
+        key: pip-${{ steps.setup_python.outputs.python-version }}-${{ steps.week_year.outputs.DATE }}-${{ hashFiles('**/requirements.txt', 'setup.py') }}
+    - name: Install Dependencies for cache
+      if: steps.venv_cache.outputs.cache-hit != 'true'
+      run: |
+        if [ -d "venv" ]; then rm -rf venv; fi
+        python3 -m venv venv
+        venv/bin/python3 -m pip install .
+        venv/bin/python3 -m pip install -r docs/requirements.txt
+    - name: Install Flax
+      run: |
+        venv/bin/python3 -m pip install -e .
+    - name: Test with ${{ matrix.test-type }}
+      run: |
+        if [[ "${{ matrix.test-type }}" == "doctest" ]]; then
+          tests/run_all_tests.sh --no-pytest --no-pytype --use-venv
+        elif [[ "${{ matrix.test-type }}" == "pytest" ]]; then
+          tests/run_all_tests.sh --no-doctest --no-pytype --with-cov --use-venv
+        elif [[ "${{ matrix.test-type }}" == "pytype" ]]; then
+          tests/run_all_tests.sh --no-doctest --no-pytest --use-venv
+        else
+          echo "Unknown test type: ${{ matrix.test-type }}"
+          exit 1
+        fi
     - name: Upload coverage to Codecov
+      if: matrix.test-type == 'pytest'
       uses: codecov/codecov-action@v1
       with:
         file: ./coverage.xml
